/* tslint:disable */
export const memory: WebAssembly.Memory;
export function start(): void;
export function __wbg_conrodcanvasexample_free(a: number): void;
export function conrodcanvasexample_new(a: number, b: number): number;
export function conrodcanvasexample_update(a: number, b: number, c: number): void;
export function conrodcanvasexample_resize(a: number, b: number, c: number): void;
export function conrodcanvasexample_mouseCursor(a: number, b: number, c: number): void;
export function conrodcanvasexample_scroll(a: number, b: number, c: number): void;
export function conrodcanvasexample_pressMouseUnknown(a: number): void;
export function conrodcanvasexample_pressMouseLeft(a: number): void;
export function conrodcanvasexample_pressMouseRight(a: number): void;
export function conrodcanvasexample_pressMouseMiddle(a: number): void;
export function conrodcanvasexample_releaseMouseUnknown(a: number): void;
export function conrodcanvasexample_releaseMouseLeft(a: number): void;
export function conrodcanvasexample_releaseMouseRight(a: number): void;
export function conrodcanvasexample_releaseMouseMiddle(a: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_start(): void;
